name: Deploy to EC2 Instanc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: SSH into EC2 and run commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.171.239.200
          username: ec2-user
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          target: CI_CD
          port: 22
          script: |
            cd CI_CD
            git pull origin main
            npm install
            npm run build
            npm run start
